//
//  ResponseOutgoing.swift
//  FB14083137
//
//  Created by Peter Clarke on 29/6/2024.
//
import Foundation

struct ResponseOutgoingMap: Codable {
    var responseOutgoing: ResponseOutgoing
}

struct ResponseOutgoing: Codable {
    var addresses: [Address]?
    var customers: [Customer]?
    var invoices: [Invoice]?
    var quotes: [Quote]?
}

struct SourceData {
    static func jsonData() -> Data? {
        return jsonString.data(using: .utf8)
    }
    
    static var jsonString =
        """
        {
        "responseOutgoing": {
        "addresses": [{
            "city": "",
            "country": "Sweden",
            "countryIsoCode": "SE",
            "email": "davva1966@gmail.com",
            "id": "4aba8d83-2e7c-4c63-9992-da78a768bbd3",
            "lastModified": 1536375146362,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "phone1": "",
            "phone2": "",
            "postCode": "",
            "reference": "",
            "stateOrTerritory": "",
            "streetAddress": "",
            "version": 1
        }, {
            "city": "",
            "country": "Sweden",
            "countryIsoCode": "SE",
            "email": "",
            "id": "0d051550-7286-4e11-b54a-c1c82c13786e",
            "lastModified": 1541227678770,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "phone1": "",
            "phone2": "",
            "postCode": "",
            "reference": "",
            "stateOrTerritory": "",
            "streetAddress": "",
            "version": 1
        }, {
            "city": "",
            "country": "Sweden",
            "countryIsoCode": "SE",
            "email": "",
            "id": "ddc9a9b6-bd7d-470b-b467-6d1cf0399da2",
            "lastModified": 1603187094696,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "phone1": "",
            "phone2": "",
            "postCode": "",
            "reference": "",
            "stateOrTerritory": "",
            "streetAddress": "",
            "version": 0
        }, {
            "city": "",
            "country": "Sweden",
            "countryIsoCode": "SE",
            "email": "",
            "id": "4630f9c5-6775-40ac-a408-c4db2848169c",
            "lastModified": 1603187094698,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "phone1": "",
            "phone2": "",
            "postCode": "",
            "reference": "",
            "stateOrTerritory": "",
            "streetAddress": "",
            "version": 0
        }, {
            "city": "",
            "country": "Sweden",
            "countryIsoCode": "SE",
            "email": "",
            "id": "085ee62f-701f-4de6-bbc0-2de5120be3eb",
            "lastModified": 1603355506983,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "phone1": "",
            "phone2": "",
            "postCode": "",
            "reference": "",
            "stateOrTerritory": "",
            "streetAddress": "",
            "version": 1
        }, {
            "city": "",
            "country": "Sweden",
            "countryIsoCode": "SE",
            "email": "",
            "id": "CF40B5B5-FE12-42DD-AC61-E73C7CC16946",
            "lastModified": 1668596564580,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "phone1": "",
            "phone2": "",
            "postCode": "",
            "reference": "",
            "stateOrTerritory": "",
            "streetAddress": "",
            "version": 1
        }, {
            "city": "",
            "country": "Sweden",
            "countryIsoCode": "SE",
            "email": "davva1966@gmail.com",
            "id": "d4187176-e53f-4ca2-9445-b1485ca0eaa4",
            "lastModified": 1704757452638,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "phone1": "",
            "phone2": "",
            "postCode": "",
            "reference": "",
            "stateOrTerritory": "",
            "streetAddress": "",
            "version": 2
        }],
        "customers": [{
            "addressId": "4aba8d83-2e7c-4c63-9992-da78a768bbd3",
            "chargeGST": true,
            "disabled": false,
            "discount": null,
            "extraInfo": "",
            "gstRegistrationNumber": "",
            "id": "f8831538-0248-4c8f-893b-200f1b545842",
            "languageId": null,
            "lastModified": 1536375078782,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "name": "Sss",
            "number": 1001,
            "paymentTerms": null,
            "printExtraInfo": true,
            "reverseGst": false,
            "version": 0
        }, {
            "addressId": "0d051550-7286-4e11-b54a-c1c82c13786e",
            "chargeGST": false,
            "disabled": false,
            "discount": null,
            "extraInfo": "",
            "gstRegistrationNumber": "123456789",
            "id": "0ba3f4f6-0cde-4c63-ad48-fa26c1663f48",
            "languageId": null,
            "lastModified": 1541297258463,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "name": "Berry",
            "number": 1002,
            "paymentTerms": null,
            "printExtraInfo": true,
            "reverseGst": false,
            "version": 2
        }, {
            "addressId": "4630f9c5-6775-40ac-a408-c4db2848169c",
            "chargeGST": true,
            "disabled": false,
            "discount": null,
            "extraInfo": "",
            "gstRegistrationNumber": "",
            "id": "e56673c9-14fe-41d0-a21a-e118f53a8cf2",
            "languageId": null,
            "lastModified": 1603187094711,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "name": "Bbb",
            "number": 1003,
            "paymentTerms": null,
            "printExtraInfo": true,
            "reverseGst": false,
            "version": 0
        }, {
            "addressId": "ddc9a9b6-bd7d-470b-b467-6d1cf0399da2",
            "chargeGST": true,
            "disabled": false,
            "discount": null,
            "extraInfo": "",
            "gstRegistrationNumber": "",
            "id": "8966d3b0-2e45-4825-b068-7828a0ebb1ba",
            "languageId": null,
            "lastModified": 1603187094732,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "name": "Aaa",
            "number": 1004,
            "paymentTerms": null,
            "printExtraInfo": true,
            "reverseGst": false,
            "version": 1
        }, {
            "addressId": "085ee62f-701f-4de6-bbc0-2de5120be3eb",
            "chargeGST": true,
            "disabled": false,
            "discount": null,
            "extraInfo": "",
            "gstRegistrationNumber": "",
            "id": "1980d105-fd39-45da-a66a-768cff259b3d",
            "languageId": null,
            "lastModified": 1603355506986,
            "lastModifiedBy": "d",
            "lastModifiedLocally": null,
            "name": "Aax",
            "number": 1005,
            "paymentTerms": null,
            "printExtraInfo": true,
            "reverseGst": false,
            "version": 1
        }],
        "invoices": [{
            "GSTDescription": "25% moms",
            "GSTDescriptionFormatted": "25% moms",
            "GSTRate": 25.00,
            "addressId": "CF40B5B5-FE12-42DD-AC61-E73C7CC16946",
            "chargeGST": true,
            "creationDate": 1668596564605,
            "creationDateMillis": 1668596564605,
            "currencyCode": "GBP",
            "customerExtraInfo": "",
            "customerId": "8966d3b0-2e45-4825-b068-7828a0ebb1ba",
            "customerSignatoryName": null,
            "customerSignatureContentBase64": null,
            "customerSignatureContentType": null,
            "customerSignatureSize": null,
            "dueDate": 1671188556000,
            "emailedOpenedDate": 1695726262000,
            "fixedPrice": 777.00,
            "gstInclusive": false,
            "gstRegistrationNumber": "",
            "hasFixedPrice": true,
            "id": "CC1DB05D-854F-4713-82F5-504003280230",
            "invoiceDate": 1668596556000,
            "isClosed": false,
            "isPaid": true,
            "lastEmailedDate": 1695723986000,
            "lastModified": 1695726264232,
            "lastModifiedBy": "anonymousUser",
            "lastModifiedLocally": null,
            "lastPrintedDate": null,
            "number": 1012,
            "paymentDate": 1704795948536,
            "printCustomerExtraInfo": true,
            "quoteId": null,
            "reference": null,
            "reverseGst": false,
            "rotApartmentId": null,
            "rotHousingSociety": null,
            "rotMaximumAmount1": 0.00,
            "rotMaximumAmount2": 0.00,
            "rotPersonalId1": null,
            "rotPersonalId2": null,
            "rotRealEstateId": null,
            "rotRutPaymentRequestNumber": null,
            "rotRutPaymentRequested": false,
            "rotRutPaymentRequestedDate": null,
            "rotRutPercent": null,
            "text": null,
            "useGst": true,
            "useRotRut": false,
            "version": 4
        }],
        "quotes": [{
            "GSTDescription": "25% moms",
            "GSTDescriptionFormatted": "25% moms",
            "GSTRate": 25.00,
            "addressId": "d4187176-e53f-4ca2-9445-b1485ca0eaa4",
            "chargeGST": false,
            "creationDate": 1678187212512,
            "creationDateMillis": 1678187212512,
            "currencyCode": "GBP",
            "customerExtraInfo": "",
            "customerId": "0ba3f4f6-0cde-4c63-ad48-fa26c1663f48",
            "customerSignatoryName": "",
            "customerSignatureContentBase64": null,
            "customerSignatureContentType": "",
            "customerSignatureSize": null,
            "emailedOpenedDate": 1704757492000,
            "fixedPrice": 77.00,
            "gstInclusive": false,
            "gstRegistrationNumber": "123456789",
            "hasFixedPrice": true,
            "id": "30c13c05-93dd-4eb8-aa1a-9db285b61d3a",
            "invoiceId": null,
            "isClosed": false,
            "lastEmailedDate": 1704757457000,
            "lastModified": 1704757493789,
            "lastModifiedBy": "anonymousUser",
            "lastModifiedLocally": null,
            "lastPrintedDate": 1696319709000,
            "number": 1004,
            "printCustomerExtraInfo": true,
            "quoteDate": 1678147200000,
            "reference": "sad",
            "reverseGst": false,
            "rotApartmentId": null,
            "rotHousingSociety": null,
            "rotMaximumAmount1": 0.00,
            "rotMaximumAmount2": 0.00,
            "rotPersonalId1": "",
            "rotPersonalId2": "",
            "rotRealEstateId": "",
            "rotRutPercent": 50.00,
            "text": "",
            "useGst": true,
            "useRotRut": false,
            "validUntil": 1685919600000,
            "version": 9
        }]
        }
        }
        """
}
